# Generated by Django 2.2.6 on 2021-01-15 10:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anger',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='christian',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='coronavirus',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='death',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='family',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='famous',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='life',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='love',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='nature',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='sad',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
        migrations.AddField(
            model_name='spiritual',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://unsplash.com/photos/zhgj7ZEUf1w', max_length=255, verbose_name='profile_pics'),
        ),
    ]
